### PR TITLE
Merge the two Identity Providers & code refactoring

### LINKED ISSUE #11: Merge the two France Connect provider
Simplify administration by merging the 2 providers and add a switch to choose between test and prod.

### PR DESCRIPTION
**Pull request by mboisnard**
Resolves #11 

- Add FranceConnect environment selector in partial
- Remove FranceConnect Test Identity Provider
- Add Enums to represent Environment and Eidas Level
- Refactor existing code and create packages

Please update the authorized redirect_uri for INSEE Test account after merging this PR.

### CODE REVIEW

**Comment by mboisnard** [comment]
Travis CI is failing due to maven plugin downloading error (Connection timeout) ... 
Please restart the CI :)

**Comment by micedre** [comment]
Thanks for the PR and sorry for the delay. At first look it seems fine to me. Could you update the README(s) with a doc on migration (eg, if we already have configured the Test provider, what happens on update?) ?

**Comment by mboisnard** [comment]
Readme(s) update done for migration process and I made some updates with the readme format:
- Compatibility section (keycloak compatible version can be change if you want, actual : from 4.5.0 with 4.8.0 exception, in this PR: from 4.8.1.Final)
- Installation process
- Requirements
- Mappers configuration

**Comment by micedre** [comment]
Thank you for all that work, could I ask you to rebase on the last master?

**Comment by mboisnard** [comment]
> Thank you for all that work, could I ask you to rebase on the last master?

Done :)

**Pull request merged**
