### PR TITLE
[FIX] Compatibility Keycloak 21

### PR DESCRIPTION
**Pull request by clement-dufaure**

### CODE REVIEW

**Comment by clement-dufaure** [comment]
Fix #85

**Comment by mboisnard** [comment]
Hey :)
I think there is a blocker with Keycloak 21 version since the Keycloak team removed the old admin interface without implementing custom provider page in the new interface.

**Comment by clement-dufaure** [comment]
Thanks to external tests, it seems that actual config is not impacted by upgrading to kc 21 and upgrading to this version of plugin france connect.
I'll probably publish this release with a huge warning, like "only for bumping from an older keycloak version but no longer settable in admin ui"

**Comment by WardLootens** [comment]
I can confirm that, with the 5.0.0-SNAPSHOT build, I was able to build and run the provider in Keycloak 21.
The existing config still works,
but indeed, I was no longer able to store the configuration from the Admin UI (I could view it, though)

**Pull request merged**
